parameters:
    # ...

services:
    logger:
        class: SEEQMGMD\Log\Logger
        arguments:
            - %appDir%/logs

    messenger:
        class: SEEQMGMD\Messenger
        arguments:
            - @logger
