parameters:
    # ...

services:
    logger:
        class: SEEQMGMD\Log\Logger
        arguments:
            - %appDir%/logs

    dispatcher:
        class: SEEQMGMD\Dispatcher
        arguments:
            - @service_container

    controller:
        class: SEEQMGMD\Controller
        arguments:
            - @service_container
            - @logger

    status_manager:
        class: SEEQMGMD\Service\StatusManager
